resolver: lts-13.8

packages:
- .

extra-deps:
- megaparsec-7.0.4
- parser-combinators-1.0.1
- unbound-generics-0.4.0
- containers-0.6.0.1
- mtl-2.2.2
- pretty-1.1.3.6
- optparse-applicative-0.14.3.0
- text-1.2.3.1
